#!/usr/bin/env python3
"""Regenerates every launcher icon and web icon from the two brand masters.

Why a script and not `flutter_launcher_icons`: this app resolves everything it can
without adding a dependency (see `backend/src/utils/pdf.ts` and `tagSticker.ts` for
the same reasoning on the server), and the icon job here is small enough to read in
one sitting — a resize, a colour, and three small XML files.

Run it from anywhere:  python3 mobile/tool/generate_app_icons.py

Inputs, both committed:

  assets/brand/app-icon.png   the designed tile: the mark on the brand navy, opaque
  assets/brand/app-mark.png   the mark alone on transparency

Outputs:

  android/app/src/main/res/mipmap-*/ic_launcher.png            legacy launcher icon
  android/app/src/main/res/mipmap-*/ic_launcher_foreground.png adaptive foreground
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml   adaptive icon
  android/app/src/main/res/values/ic_launcher_background.xml   the background colour
  web/icons/*.png                                              PWA icons + favicon

Requires Pillow (`python3 -m pip install pillow`).
"""

from __future__ import annotations

import pathlib

import numpy as np
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parents[1]
MASTER = ROOT / "assets/brand/app-icon.png"
MARK = ROOT / "assets/brand/app-mark.png"
RES = ROOT / "android/app/src/main/res"
WEB_ICONS = ROOT / "web/icons"

# The navy the master's own background is painted in — sampled, not guessed, so the
# adaptive background layer cannot leave a visible square edge behind the round mask.
BACKGROUND = "#013C67"

# Legacy icons are drawn at the launcher's size. Adaptive layers are 108dp with only
# the middle 72dp guaranteed visible, so the mark is scaled to live inside that.
LEGACY_SIZES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
ADAPTIVE_SIZES = {"mdpi": 108, "hdpi": 162, "xhdpi": 216, "xxhdpi": 324, "xxxhdpi": 432}
SAFE_FRACTION = 0.62

# A 512px maskable icon may be masked down to a circle 80% of its width, and the
# corners are always cropped: the mark has to be that much smaller again.
MASKABLE_SAFE_FRACTION = 0.60

ALPHA_THRESHOLD = 25


def load_rgba(path: pathlib.Path) -> Image.Image:
    return Image.open(path).convert("RGBA")


def mark_bounds(mark: Image.Image) -> tuple[int, int, int, int]:
    """The mark's real bounding box.

    Measured rather than assumed: the master's mark does not fill its canvas, and an
    icon built from an assumed box would ship the wrong amount of padding. The
    threshold skips the near-transparent edge pixels that a non-zero test would count.
    """
    alpha = np.array(mark)[:, :, 3]
    ys, xs = np.where(alpha > ALPHA_THRESHOLD)
    return int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1


def centred_mark(mark: Image.Image, size: int, fraction: float) -> Image.Image:
    """The mark, scaled to `fraction` of a square canvas and centred on transparency."""
    cropped = mark.crop(mark_bounds(mark))
    target = round(size * fraction)
    scale = target / max(cropped.width, cropped.height)
    scaled = cropped.resize(
        (max(1, round(cropped.width * scale)), max(1, round(cropped.height * scale))),
        Image.LANCZOS,
    )

    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(scaled, ((size - scaled.width) // 2, (size - scaled.height) // 2))
    return canvas


#
# There is deliberately no `monochrome` layer, so no themed-icon silhouette is
# generated. Android tints that layer with a single colour, and the measure of it is
# the mark's **alpha**: the mark is a solid shape (74% of its bounding box, with no
# enclosed transparent area at all), because its design lives in its colour, not in
# cut-outs. A silhouette of it is therefore a featureless blob — which is exactly
# what a phone with themed icons enabled drew: one flat dark shape where the mark
# had been, the colour gone and only the edges left to see. With no monochrome
# layer the launcher keeps the real icon instead of inventing a worse version of it;
# `centred_mark` above is what draws the layer we do ship.


def save(image: Image.Image, path: pathlib.Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True)
    print(f"  {path.relative_to(ROOT)}  {image.width}x{image.height}")


def write_adaptive_xml() -> None:
    """The adaptive icon: a flat navy background and the mark."""
    save_text(
        RES / "mipmap-anydpi-v26/ic_launcher.xml",
        """<?xml version="1.0" encoding="utf-8"?>
<!--
  Adaptive launcher icon (Android 8+). Generated by tool/generate_app_icons.py.
  The background is a flat colour rather than a bitmap so the round/squircle mask
  never reveals a square edge, and the foreground lives inside the middle 66% that
  the launcher guarantees to keep.
-->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
""",
    )

    save_text(
        RES / "values/ic_launcher_background.xml",
        f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_app_icons.py — sampled from assets/brand/app-icon.png. -->
<resources>
    <color name="ic_launcher_background">{BACKGROUND}</color>
</resources>
""",
    )


def save_text(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(ROOT)}")


def write_manifest_colours() -> None:
    """Keeps the PWA's own colours in step with the icon.

    A manifest still declaring Flutter's template blue (#0175C2) makes the installed
    shortcut's splash and status bar the wrong colour next to the navy icon.
    """
    path = ROOT / "web/manifest.json"
    text = path.read_text(encoding="utf-8")
    for old, new in (
        ('"name": "cncs_pms_mobile"', '"name": "CNCS Property Management"'),
        ('"short_name": "cncs_pms_mobile"', '"short_name": "CNCS PMS"'),
        ('"#0175C2"', f'"{BACKGROUND}"'),
    ):
        text = text.replace(old, new)
    path.write_text(text, encoding="utf-8")
    print(f"  {path.relative_to(ROOT)} (name, short name and theme colour)")


def main() -> None:
    master = load_rgba(MASTER)
    mark = load_rgba(MARK)

    print("Android legacy icons")
    for density, size in LEGACY_SIZES.items():
        save(master.resize((size, size), Image.LANCZOS).convert("RGB"),
             RES / f"mipmap-{density}/ic_launcher.png")

    print("Android adaptive layers")
    for density, size in ADAPTIVE_SIZES.items():
        save(centred_mark(mark, size, SAFE_FRACTION),
             RES / f"mipmap-{density}/ic_launcher_foreground.png")
        # Themed-icon silhouettes are removed, and stale ones are deleted: see the
        # note above `main()` for why an alpha silhouette of this mark is unusable.
        (RES / f"mipmap-{density}/ic_launcher_monochrome.png").unlink(missing_ok=True)

    print("Android resource files")
    write_adaptive_xml()

    print("Web manifest")
    write_manifest_colours()

    print("Web icons")
    save(master.resize((512, 512), Image.LANCZOS).convert("RGB"), WEB_ICONS / "Icon-512.png")
    save(master.resize((192, 192), Image.LANCZOS).convert("RGB"), WEB_ICONS / "Icon-192.png")

    # Maskable icons are composited on the same navy rather than using the tile, so
    # the mark survives the circular mask instead of being cropped by it.
    navy = Image.new("RGBA", (512, 512), BACKGROUND + "FF")
    navy.alpha_composite(centred_mark(mark, 512, MASKABLE_SAFE_FRACTION))
    save(navy.convert("RGB"), WEB_ICONS / "Icon-maskable-512.png")
    save(navy.convert("RGB").resize((192, 192), Image.LANCZOS),
         WEB_ICONS / "Icon-maskable-192.png")

    save(master.resize((32, 32), Image.LANCZOS).convert("RGB"), ROOT / "web/favicon.png")

    print("\nDone. Rebuild the app for the launcher to show the new icon.")


if __name__ == "__main__":
    main()
